version: '3.8'
services:
  app:
    image: ghcr.io/maamokun/airtifacter
    ports:
      - '3000:3000'
    volumes:
      - './.env:/app/.env'
      - './config:/app/config'
      - './cache:/app/cache'
      - './data:/app/data'
    command: sh -c "npm run build && npm start"
  generate:
    image: ghcr.io/maamokun/airtifacter
    volumes:
      - './.env:/app/.env'
      - './config:/app/config'
      - './cache:/app/cache'
      - './data:/app/data'
    command: npm run generate
