version: '3.8'
services:
  app:
    image: ghcr.io/maamokun/airtifacter
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "pnpm install && pnpm run build && pnpm start"
  generate:
    image: ghcr.io/maamokun/airtifacter
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "pnpm install && pnpm run generate"